name: Test Preprocessing

on: [push, pull_request]

jobs:
    test:

        runs-on: ubuntu-20.04
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install Miniconda
          run: |
            bash miniconda_setup.sh
            export PATH="/home/runner/miniconda3/bin:$PATH"
            source ~/.bashrc
            
    
        - name: Create Conda environment
          shell: bash
          run: |
            source /home/runner/miniconda3/bin/activate
            conda init bash
            conda env create -f environment.yml -n samal
            echo "env created"
            conda activate samal
    
