name: Test Preprocessing

on: [push, pull_request]

jobs:
    test:

        runs-on: ubuntu-20.04
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install Miniconda
          run: |
            bash miniconda_setup.sh
    
        - name: Create Conda environment
          shell: bash
          run: |
            conda env create -f environment.yml -n samal
            echo "env created"
            conda $CONDA/bin/activate samal
    