name: Test Preprocessing

on: [push, pull_request]

jobs:
    test:

        runs-on: ubuntu-20.04
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install Miniconda
          run: |
            bash ${{ github.workspace }}/miniconda-setup.sh -b -p $HOME/miniconda
            source "$HOME/miniconda/etc/profile.d/conda.sh"
    
        - name: Create Conda environment
          run: |
            conda env create -f ${{ github.workspace }}/environment.yml
            conda activate myenv
    